- hosts: all
  name: Autoconverted job legacy-bashate-devstack from old job gate-bashate-devstack
  roles:
    - bindep

  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd $WORKSPACE

          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            https://git.openstack.org \
            openstack-dev/bashate \
            openstack-dev/devstack \
            openstack-infra/devstack-gate

          export BASHATE_INSTALL_PATH=$WORKSPACE/openstack-dev/bashate

          pushd openstack-dev/devstack
          tox -e bashate
          popd

          pushd openstack-infra/devstack-gate
          tox -e bashate
          popd
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
